// Maritime routes among the G20. Generated by the Fase 0 pipeline
// (scripts/ingest-searoute.mjs -> generated/sea-routes.json): real sea routes
// computed by searoute-js (through the actual marine network — canals/straits,
// avoiding land) between the main ports of each country, weighted by real
// UN Comtrade trade values. Re-run `npm run ingest:searoute` to refresh.

import generated from "./generated/sea-routes.json";

export interface SeaLane {
  from: number; // origin ISO
  to: number; // destination ISO
  value: number; // annual trade value, USD billions (drives ship count/thickness)
  waypoints: Array<[number, number]>; // [lat, lng] along the real sea route
}

/** As-of date + provenance of the generated sea routes. */
export const SEA_META = { asOf: generated.asOf, source: generated.source };

export const SEA_LANES: SeaLane[] = generated.routes as unknown as SeaLane[];
