// Bilateral trade flows among the G20 (directional exporter -> importer, annual
// value in USD billions). Generated by the Fase 0 pipeline
// (scripts/ingest-trade.mjs -> generated/trade-flows.json) from UN Comtrade.
// Drives the air-route selection and the flow density on the globe.

import generated from "./generated/trade-flows.json";

export interface TradeFlow {
  from: number; // exporter ISO
  to: number; // importer ISO
  value: number; // annual, USD billions
}

/** As-of date + provenance of the generated trade snapshot. */
export const TRADE_META = { asOf: generated.asOf, period: generated.period, source: generated.source };

export const TRADE_FLOWS: TradeFlow[] = generated.flows as unknown as TradeFlow[];
